services:
  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: local
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
